name: Code Generation

on:
    push:
        paths:
        - 'Lex/**'
        - 'Parser/**'
        - 'Semantic/**'
        - 'CodeGen/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Add LLVM APT Repository
          run: |
            sudo apt-get update
            sudo apt-get install -y wget lsb-release software-properties-common
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 18
        
        - name: Install SFML
          run: sudo apt install libopenal-dev libsndfile1-dev libsfml-dev