name: Code Generation

on:
    push:
        paths:
        - 'Lex/**'
        - 'Parser/**'
        - 'Semantic/**'
        - 'CodeGen/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Add LLVM APT Repository
          run: |
            sudo apt-get update
            sudo apt-get install -y wget lsb-release software-properties-common
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 18

        - name: Verify Clang 18 Installation
          run: |
            clang-18 --version
            llvm-config-18 --version

        - name: Build Code Generation
          run: cd CodeGen && make
    
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Run Tests
          run: cd CodeGen && make test